export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_INITIATED = 'CREATE_ARTICLE_INITIATED';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';

export const GET_ALL_ARTICLES_SUCCESS = 'GET_ALL_ARTICLES_SUCCESS';
export const GET_ALL_ARTICLES_INITIATED = 'GET_ALL_ARTICLES_INITIATED';

export const GET_SPECIFIC_ARTICLE_SUCCESS = 'GET_SPECIFIC_ARTICLE_SUCCESS';
export const GET_SPECIFIC_ARTICLE_INITIATED = 'GET_SPECIFIC_ARTICLE_INITIATED';

export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_ERROR = 'EDIT_ARTICLE_ERROR';
export const EDIT_ARTICLE_INITIATED = 'EDIT_ARTICLE_INITIATED';

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
