export const profileActionTypes = {
  SAVE_PROFILE: 'SAVE_PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',
  PROFILE_FETCH: 'PROFILE_FETCH',
  PROFILE_FETCHED: 'PROFILE_FETCHED',
  FOLLOWING_FETCHED: 'FOLLOWING_FETCHED',
  FOLLOWERS_FETCHED: 'FOLLOWERS_FETCHED',
  CANCEL_EDIT: 'CANCEL_EDIT',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
};
