export const HIGHLIGHT_SUCCESS= 'HIGHLIGHT_SUCCESS';
export const HIGHLIGHT_FAILURE= 'HIGHLIGHT_FAILURE';

export const SAVE_HIGHLIGHT_SUCCESS= 'SAVE_HIGHLIGHT_SUCCESS';
export const SAVE_HIGHLIGHT_FAILURE= 'SAVE_HIGHLIGHT_FAILURE';

export const GET_HIGHLIGHT_SUCCESS= 'GET_HIGHLIGHT_SUCCESS';
export const GET_HIGHLIGHT_FAILURE= 'GET_HIGHLIGHT_FAILURE';

export const COMMENT_HIGHLIGHT_SUCCESS= 'COMMENT_HIGHLIGHT_SUCCESS';
export const COMMENT_HIGHLIGHT_FAILURE= 'COMMENT_HIGHLIGHT_FAILURE';