export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAILURE = 'COMMENT_POST_FAILURE';

export const COMMENT_GET_SUCCESS = 'COMMENT_GET_SUCCESS';
export const COMMENT_GET_FAILURE = 'COMMENT_GET_FAILURE';

export const REPLY_POST_SUCCESS = 'REPLY_POST_SUCCESS';
export const REPLY_POST_FAILURE = 'REPLY_POST_FAILURE';

