export const LIKE_ARTICLE = 'LIKE_ARTICLE';
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';

export const UNLIKE_ARTICLE = 'UNLIKE_ARTICLE';
export const UNLIKE_ARTICLE_SUCCESS = 'UNLIKE_ARTICLE_SUCCESS';
export const UNLIKE_ARTICLE_FAILURE = 'UNLIKE_ARTICLE_FAILURE';
