export const RESET_PASSWORD_ACTION = 'RESET_PASSWORD_ACTION';
export const RESET_PASSWORD_ACTION_SUCCESS = 'RESET_PASSWORD_ACTION_SUCCESS';
export const RESET_PASSWORD_ACTION_FAILURE = 'RESET_PASSWORD_ACTION_FAILURE';
